version: '3'

services:
  web:
    build:
      context: ./web
    container_name: saml_web
    depends_on:
      - idp
    ports:
      - '9100:9100'
    environment:
      HOSTNAME: ${HOSTNAME:-localhost} 
      HOST_ABSOLUTE_PATH: ${HOST_ABSOLUTE_PATH:-$PWD}
    networks:
      web_lab_my_network:
        aliases:
          - saml_network
    volumes:
      - ${HOST_ABSOLUTE_PATH:-$PWD}/users.php:/app/users.php
      - ${HOST_ABSOLUTE_PATH:-$PWD}/users.json:/app/users.json
      #- ./users.php:/app/users.php
      #- ./users.json:/app/users.json
  idp:
    image: kristophjunge/test-saml-idp
    #build:
    #  context: ./saml-idp
    container_name: saml_idp
    ports:
      - '9200:8080'
    networks:
      web_lab_my_network:
        aliases:
          - saml_network
    environment:
      HOSTNAME: ${HOSTNAME:-localhost} 
      HOST_ABSOLUTE_PATH: ${HOST_ABSOLUTE_PATH:-$PWD}
      SIMPLESAMLPHP_SP_ENTITY_ID: 'saml-poc'
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: "http://${HOSTNAME}:9100/login/callback"
      #SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: 'http://website:9100/acs'
      #SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: 'http://website:9100/logout'
      #SIMPLESAMLPHP_SP_NAMEID_FORMAT: 'urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified'
      #SIMPLESAMLPHP_IDP_ENTITY_ID: 'http://localhost:9200/saml/idp/metadata.php'
      #SIMPLESAMLPHP_IDP_SINGLE_SIGN_ON_SERVICE: 'http://localhost:9200/saml/idp/ssocircle.php'
      #SIMPLESAMLPHP_IDP_SINGLE_LOGOUT_SERVICE: 'http://localhost:9200/saml/idp/sls.php'
    volumes:
      - ${HOST_ABSOLUTE_PATH:-$PWD}/users.php:/var/www/simplesamlphp/config/authsources.php
      #- ./users.php:/var/www/simplesamlphp/config/authsources.php

networks:
  web_lab_my_network:
      external: true