version: '3.8'
services:
  api:
    build: ./api
    container_name: api_backend
    ports:
      - '8080:8080'
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=mydatabase
  client:
    build: ./client
    container_name: client_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  db:
    image: postgres:13
    container_name: postgres_database
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
