version: '3'
services:
  web:
    build: 
      context: ./web
    container_name: ede_web
    restart: always
    ports:
      - "9400:9400"
    environment:
      - DB_HOST=ede_db
      - DB_USER=postgres
      - DB_PASSWORD=mypassword
      - DB_NAME=ede_db
    depends_on:
      - db
    networks:
      web_lab_my_network:
        aliases:
          - ede_network
  db:
    build: 
      context: ./db
      dockerfile: Dockerfile.db
    container_name: ede_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=ede_db
    networks:
      web_lab_my_network:
        aliases:
          - ede_network
networks:
  web_lab_my_network:
      external: true