version: '3'

services:   
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ilm_web
    restart: always
    ports:
      - "9800:9800"
    networks:
      web_lab_my_network:
        aliases:
          - ilm_network

networks:
  web_lab_my_network:
      external: true